version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace
      - run: echo "//registry.npmjs.org:/:authToken=$npm_TOKEN" > ${CIRCLE_WORKING_DIRECTORY}/.npmrc
      - run: npm publish


workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
