version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo "//registry.npmjs.org:/:authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run: npm publish


workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - master
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
